# Generated by Django 5.1.7 on 2025-03-14 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image_urls', models.JSONField(default=list)),
                ('ratings', models.FloatField()),
                ('description', models.TextField()),
                ('num_reviews', models.IntegerField()),
                ('amenities', models.JSONField(default=list)),
                ('host_info', models.JSONField(default=dict)),
                ('property_type', models.CharField(max_length=50)),
            ],
        ),
    ]
